# Generated by Django 3.2.9 on 2022-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCodeBD', '0003_auto_20220418_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
