# Generated by Django 3.2.9 on 2022-04-18 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeoCodeBD', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_bn', models.CharField(max_length=200)),
                ('care_of', models.CharField(choices=[('', '-- Select --'), ('Father', 'Father'), ('Husband', 'Husband')], max_length=100)),
                ('care_of_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('care_of_name_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('', '-- Select --'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('blood_group', models.CharField(choices=[('', '-- Select --'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('nid_no', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('present_address_en', models.CharField(blank=True, max_length=200, null=True)),
                ('present_address_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('present_area_village_en', models.CharField(blank=True, max_length=200, null=True)),
                ('present_area_village_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('present_post_code', models.CharField(blank=True, max_length=100, null=True)),
                ('residence_status', models.CharField(blank=True, choices=[('', '--Select--'), ('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=100, null=True)),
                ('permanent_address_en', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_address_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_area_village_en', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_area_village_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_post_code', models.CharField(blank=True, max_length=100, null=True)),
                ('nid_birth_reg_image', models.ImageField(blank=True, null=True, upload_to='nid_image')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('electricity_bill_image', models.ImageField(blank=True, null=True, upload_to='electrical_bill_image')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_by', to=settings.AUTH_USER_MODEL)),
                ('permanent_district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GeoCodeBD.district')),
                ('permanent_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GeoCodeBD.division')),
                ('permanent_post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GeoCodeBD.union')),
                ('permanent_thana', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GeoCodeBD.upazila')),
                ('present_district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='present_district', to='GeoCodeBD.district')),
                ('present_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='present_division', to='GeoCodeBD.division')),
                ('present_post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='present_post_office', to='GeoCodeBD.union')),
                ('present_thana', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='present_thana', to='GeoCodeBD.upazila')),
            ],
        ),
    ]
