# Generated by Django 3.2.9 on 2022-04-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name_bn',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
